social_auth_yahoo.settings:
  type: config_object
  label: 'Social Auth Yahoo settings'
  mapping:
    app_key:
      type: string
      label: 'App Key'
    app_secret:
      type: string
      label: 'App Secret'
    endpoints:
      type: string
      label: 'API Endpoints to be requested'
